spring:
    datasource:
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000;druid.stat.logSlowSql=true;
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 2000
            max-wait-thread-count: 3000
            stat-view-servlet:
                login-password: august
                login-username: august123
        url:
        username:
        password:
logging:
  level:
    org.springframework.web: INFO
  path: /www/wwwlogs/august
  file: ${server.context-path}.${server.port}

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger
swagger.enabled: false

# dingtalk
dingtalk.webhook: https://oapi.dingtalk.com/robot/send?access_token=718766ec52401387062804c24af4931267b0bbe455549f88c1c89267f5c4b039
dingtalk.enabled: false
