eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
#          defaultZone: http://${eureka.instance.instance-id}/eureka/
          defaultZone: http://eureka.didispace.com/eureka/

spring:
  rabbitmq:
    host: 192.168.0.108
    port: 5672
    username: guest
    password: guest
  redis:
    host:
    port: 6379
    database: 1
    password:
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 1