eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    registerWithEureka: false  # 该服务不会想enreka server注册
    fetchRegistry: false # 该服务不向eureka server获取服务
    service-url:
          defaultZone: http://${eureka.instance.instance-id}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0  # 服务器节点的状态信息被更新的时间间隔，单位为毫秒，默认为30 * 1000
    enable-self-preservation: false # 自我保护机制