-- ----------------------------
-- Records of t_sys_dept
-- ----------------------------
INSERT INTO `t_sys_dept` VALUES ('6', '0', '研发部', '1', '1');
INSERT INTO `t_sys_dept` VALUES ('7', '6', '研發一部', '1', '1');
INSERT INTO `t_sys_dept` VALUES ('8', '6', '研发二部', '2', '1');
INSERT INTO `t_sys_dept` VALUES ('9', '0', '销售部', '2', '1');
INSERT INTO `t_sys_dept` VALUES ('10', '9', '销售一部', '1', '1');
INSERT INTO `t_sys_dept` VALUES ('11', '0', '产品部', '3', '1');
INSERT INTO `t_sys_dept` VALUES ('12', '11', '产品一部', '1', '1');
INSERT INTO `t_sys_dept` VALUES ('13', '0', '测试部', '5', '1');
INSERT INTO `t_sys_dept` VALUES ('14', '13', '测试一部', '1', '1');
INSERT INTO `t_sys_dept` VALUES ('15', '13', '测试二部', '2', '1');


-- ----------------------------
-- Records of t_sys_dict
-- ----------------------------
INSERT INTO `t_sys_dict` VALUES ('1', '正常', '0', 'del_flag', '删除标记', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('3', '显示', '1', 'show_hide', '显示/隐藏', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('4', '隐藏', '0', 'show_hide', '显示/隐藏', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('5', '是', '1', 'yes_no', '是/否', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('6', '否', '0', 'yes_no', '是/否', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('7', '红色', 'red', 'color', '颜色值', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('8', '绿色', 'green', 'color', '颜色值', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('9', '蓝色', 'blue', 'color', '颜色值', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('10', '黄色', 'yellow', 'color', '颜色值', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('11', '橙色', 'orange', 'color', '颜色值', '50', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('12', '默认主题', 'default', 'theme', '主题方案', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('13', '天蓝主题', 'cerulean', 'theme', '主题方案', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('14', '橙色主题', 'readable', 'theme', '主题方案', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('15', '红色主题', 'united', 'theme', '主题方案', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('16', 'Flat主题', 'flat', 'theme', '主题方案', '60', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('17', '国家', '1', 'sys_area_type', '区域类型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('18', '省份、直辖市', '2', 'sys_area_type', '区域类型', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('19', '地市', '3', 'sys_area_type', '区域类型', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('20', '区县', '4', 'sys_area_type', '区域类型', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('21', '公司', '1', 'sys_office_type', '机构类型', '60', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('22', '部门', '2', 'sys_office_type', '机构类型', '70', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('23', '小组', '3', 'sys_office_type', '机构类型', '80', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('24', '其它', '4', 'sys_office_type', '机构类型', '90', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('25', '综合部', '1', 'sys_office_common', '快捷通用部门', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('26', '开发部', '2', 'sys_office_common', '快捷通用部门', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('27', '人力部', '3', 'sys_office_common', '快捷通用部门', '50', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('28', '一级', '1', 'sys_office_grade', '机构等级', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('29', '二级', '2', 'sys_office_grade', '机构等级', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('30', '三级', '3', 'sys_office_grade', '机构等级', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('31', '四级', '4', 'sys_office_grade', '机构等级', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('32', '所有数据', '1', 'sys_data_scope', '数据范围', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('33', '所在公司及以下数据', '2', 'sys_data_scope', '数据范围', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('34', '所在公司数据', '3', 'sys_data_scope', '数据范围', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('35', '所在部门及以下数据', '4', 'sys_data_scope', '数据范围', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('36', '所在部门数据', '5', 'sys_data_scope', '数据范围', '50', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('37', '仅本人数据', '8', 'sys_data_scope', '数据范围', '90', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('38', '按明细设置', '9', 'sys_data_scope', '数据范围', '100', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('39', '系统管理', '1', 't_sys_user_type', '用户类型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('40', '部门经理', '2', 't_sys_user_type', '用户类型', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('41', '普通用户', '3', 't_sys_user_type', '用户类型', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('42', '基础主题', 'basic', 'cms_theme', '站点主题', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('43', '蓝色主题', 'blue', 'cms_theme', '站点主题', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('44', '红色主题', 'red', 'cms_theme', '站点主题', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('45', '文章模型', 'article', 'cms_module', '栏目模型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('46', '图片模型', 'picture', 'cms_module', '栏目模型', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('47', '下载模型', 'download', 'cms_module', '栏目模型', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('48', '链接模型', 'link', 'cms_module', '栏目模型', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('49', '专题模型', 'special', 'cms_module', '栏目模型', '50', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('50', '默认展现方式', '0', 'cms_show_modes', '展现方式', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('51', '首栏目内容列表', '1', 'cms_show_modes', '展现方式', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('52', '栏目第一条内容', '2', 'cms_show_modes', '展现方式', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('53', '发布', '0', 'cms_del_flag', '内容状态', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('54', '删除', '1', 'cms_del_flag', '内容状态', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('55', '审核', '2', 'cms_del_flag', '内容状态', '15', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('56', '首页焦点图', '1', 'cms_posid', '推荐位', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('57', '栏目页文章推荐', '2', 'cms_posid', '推荐位', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('58', '咨询', '1', 'cms_guestbook', '留言板分类', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('59', '建议', '2', 'cms_guestbook', '留言板分类', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('60', '投诉', '3', 'cms_guestbook', '留言板分类', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('61', '其它', '4', 'cms_guestbook', '留言板分类', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('62', '公休', '1', 'oa_leave_type', '请假类型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('63', '病假', '2', 'oa_leave_type', '请假类型', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('64', '事假', '3', 'oa_leave_type', '请假类型', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('65', '调休', '4', 'oa_leave_type', '请假类型', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('66', '婚假', '5', 'oa_leave_type', '请假类型', '60', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('67', '接入日志', '1', 't_sys_track_record_type', '日志类型', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('68', '异常日志', '2', 't_sys_track_record_type', '日志类型', '40', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('69', '请假流程', 'leave', 'act_type', '流程类型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('70', '审批测试流程', 'test_audit', 'act_type', '流程类型', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('71', '分类1', '1', 'act_category', '流程分类', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('72', '分类2', '2', 'act_category', '流程分类', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('73', '增删改查', 'crud', 'gen_category', '代码生成分类', '10', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('74', '增删改查（包含从表）', 'crud_many', 'gen_category', '代码生成分类', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('75', '树结构', 'tree', 'gen_category', '代码生成分类', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('76', '=', '=', 'gen_query_type', '查询方式', '10', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('77', '!=', '!=', 'gen_query_type', '查询方式', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('78', '&gt;', '&gt;', 'gen_query_type', '查询方式', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('79', '&lt;', '&lt;', 'gen_query_type', '查询方式', '40', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('80', 'Between', 'between', 'gen_query_type', '查询方式', '50', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('81', 'Like', 'like', 'gen_query_type', '查询方式', '60', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('82', 'Left Like', 'left_like', 'gen_query_type', '查询方式', '70', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('83', 'Right Like', 'right_like', 'gen_query_type', '查询方式', '80', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('84', '文本框', 'input', 'gen_show_type', '字段生成方案', '10', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('85', '文本域', 'textarea', 'gen_show_type', '字段生成方案', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('86', '下拉框', 'select', 'gen_show_type', '字段生成方案', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('87', '复选框', 'checkbox', 'gen_show_type', '字段生成方案', '40', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('88', '单选框', 'radiobox', 'gen_show_type', '字段生成方案', '50', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('89', '日期选择', 'dateselect', 'gen_show_type', '字段生成方案', '60', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('90', '人员选择', 'userselect', 'gen_show_type', '字段生成方案', '70', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('91', '部门选择', 'officeselect', 'gen_show_type', '字段生成方案', '80', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('92', '区域选择', 'areaselect', 'gen_show_type', '字段生成方案', '90', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('93', 'String', 'String', 'gen_java_type', 'Java类型', '10', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('94', 'Long', 'Long', 'gen_java_type', 'Java类型', '20', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('95', '仅持久层', 'dao', 'gen_category', '代码生成分类', '40', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('96', '男', '1', 'sex', '性别', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('97', '女', '2', 'sex', '性别', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('98', 'Integer', 'Integer', 'gen_java_type', 'Java类型', '30', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('99', 'Double', 'Double', 'gen_java_type', 'Java类型', '40', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('100', 'Date', 'java.util.Date', 'gen_java_type', 'Java类型', '50', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('104', 'Custom', 'Custom', 'gen_java_type', 'Java类型', '90', '0', '1', null, '1', null, null, '1');
INSERT INTO `t_sys_dict` VALUES ('105', '会议通告', '1', 'oa_notify_type', '通知通告类型', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('106', '奖惩通告', '2', 'oa_notify_type', '通知通告类型', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('107', '活动通告', '3', 'oa_notify_type', '通知通告类型', '30', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('108', '草稿', '0', 'oa_notify_status', '通知通告状态', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('109', '发布', '1', 'oa_notify_status', '通知通告状态', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('110', '未读', '0', 'oa_notify_read', '通知通告状态', '10', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('111', '已读', '1', 'oa_notify_read', '通知通告状态', '20', '0', '1', null, '1', null, null, '0');
INSERT INTO `t_sys_dict` VALUES ('112', '草稿', '0', 'oa_notify_status', '通知通告状态', '10', '0', '1', null, '1', null, '', '0');
INSERT INTO `t_sys_dict` VALUES ('113', '删除', '0', 'del_flag', '删除标记', null, null, null, null, null, null, '', '');
INSERT INTO `t_sys_dict` VALUES ('118', '关于', 'about', 'blog_type', '博客类型', null, null, null, null, null, null, '全url是:/blog/open/page/about', '');
INSERT INTO `t_sys_dict` VALUES ('119', '交流', 'communication', 'blog_type', '博客类型', null, null, null, null, null, null, '', '');
INSERT INTO `t_sys_dict` VALUES ('120', '文章', 'article', 'blog_type', '博客类型', null, null, null, null, null, null, '', '');
INSERT INTO `t_sys_dict` VALUES ('121', '编码', 'code', 'hobby', '爱好', null, null, null, null, null, null, '', '');
INSERT INTO `t_sys_dict` VALUES ('122', '绘画', 'painting', 'hobby', '爱好', null, null, null, null, null, null, '', '');


-- ----------------------------
-- Records of t_sys_menu
-- ----------------------------
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (1, 0, '基础管理', '', '', 0, 'fa fa-bars', 0, '2017-08-09 22:49:47', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (2, 3, '系统菜单', 'sys/menu/', 'sys:menu:menu', 1, 'fa fa-th-list', 2, '2017-08-09 22:55:15', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (3, 0, '系统管理', NULL, NULL, 0, 'fa fa-desktop', 1, '2017-08-09 23:06:55', '2017-08-14 14:13:43');
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (6, 3, '用户管理', 'sys/user/', 'sys:user:user', 1, 'fa fa-user', 0, '2017-08-10 14:12:11', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (7, 3, '角色管理', 'sys/role', 'sys:role:role', 1, 'fa fa-paw', 1, '2017-08-10 14:13:19', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (12, 6, '新增', '', 'sys:user:add', 2, '', 0, '2017-08-14 10:51:35', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (13, 6, '编辑', '', 'sys:user:edit', 2, '', 0, '2017-08-14 10:52:06', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (14, 6, '删除', NULL, 'sys:user:remove', 2, NULL, 0, '2017-08-14 10:52:24', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (15, 7, '新增', '', 'sys:role:add', 2, '', 0, '2017-08-14 10:56:37', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (20, 2, '新增', '', 'sys:menu:add', 2, '', 0, '2017-08-14 10:59:32', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (21, 2, '编辑', '', 'sys:menu:edit', 2, '', 0, '2017-08-14 10:59:56', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (22, 2, '删除', '', 'sys:menu:remove', 2, '', 0, '2017-08-14 11:00:26', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (24, 6, '批量删除', '', 'sys:user:batchRemove', 2, '', 0, '2017-08-14 17:27:18', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (25, 6, '停用', NULL, 'sys:user:disable', 2, NULL, 0, '2017-08-14 17:27:43', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (26, 6, '重置密码', '', 'sys:user:resetPwd', 2, '', 0, '2017-08-14 17:28:34', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (27, 91, '系统日志', 'common/log', 'common:log', 1, 'fa fa-warning', 0, '2017-08-14 22:11:53', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (28, 27, '刷新', NULL, 'sys:log:list', 2, NULL, 0, '2017-08-14 22:30:22', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (29, 27, '删除', NULL, 'sys:log:remove', 2, NULL, 0, '2017-08-14 22:30:43', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (30, 27, '清空', NULL, 'sys:log:clear', 2, NULL, 0, '2017-08-14 22:31:02', NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (48, 77, '代码生成', 'common/generator', 'common:generator', 1, 'fa fa-code', 3, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (49, 0, '博客管理', '', '', 0, 'fa fa-rss', 6, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (50, 49, '文章列表', 'blog/bContent', 'blog:bContent:bContent', 1, 'fa fa-file-image-o', 1, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (51, 50, '新增', '', 'blog:bContent:add', 2, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (55, 7, '编辑', '', 'sys:role:edit', 2, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (56, 7, '删除', '', 'sys:role:remove', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (57, 91, '运行监控', 'druid/index.html', '', 1, 'fa fa-caret-square-o-right', 1, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (58, 50, '编辑', '', 'blog:bContent:edit', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (59, 50, '删除', '', 'blog:bContent:remove', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (60, 50, '批量删除', '', 'blog:bContent:batchRemove', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (61, 2, '批量删除', '', 'sys:menu:batchRemove', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (62, 7, '批量删除', '', 'sys:role:batchRemove', 2, NULL, NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (68, 49, '发布文章', 'blog/bContent/add', 'blog:bContent:add', 1, 'fa fa-edit', 0, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (71, 1, '文件管理', 'common/sysFile', 'common:sysFile:sysFile', 1, 'fa fa-folder-open', 2, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (72, 77, '计划任务', 'common/job', 'common:taskScheduleJob', 1, 'fa fa-hourglass-1', 4, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (73, 3, '部门管理', 'system/sysDept', 'system:sysDept:sysDept', 1, 'fa fa-users', 3, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (74, 73, '增加', '/system/sysDept/add', 'system:sysDept:add', 2, NULL, 1, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (75, 73, '刪除', 'system/sysDept/remove', 'system:sysDept:remove', 2, NULL, 2, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (76, 73, '编辑', '/system/sysDept/edit', 'system:sysDept:edit', 2, NULL, 3, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (77, 0, '系统工具', '', '', 0, 'fa fa-gear', 4, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (78, 1, '数据字典', 'common/dict', 'common:dict:dict', 1, 'fa fa-book', 1, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (79, 78, '增加', '/common/dict/add', 'common:dict:add', 2, NULL, 2, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (80, 78, '编辑', '/common/dict/edit', 'common:dict:edit', 2, NULL, 2, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (81, 78, '删除', '/common/dict/remove', 'common:dict:remove', 2, '', 3, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (83, 78, '批量删除', '/common/dict/batchRemove', 'common:dict:batchRemove', 2, '', 4, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (84, 0, '办公管理', '', '', 0, 'fa fa-laptop', 5, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (85, 84, '通知公告', 'oa/notify', 'oa:notify:notify', 1, 'fa fa-pencil-square', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (86, 85, '新增', 'oa/notify/add', 'oa:notify:add', 2, 'fa fa-plus', 1, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (87, 85, '编辑', 'oa/notify/edit', 'oa:notify:edit', 2, 'fa fa-pencil-square-o', 2, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (88, 85, '删除', 'oa/notify/remove', 'oa:notify:remove', 2, 'fa fa-minus', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (89, 85, '批量删除', 'oa/notify/batchRemove', 'oa:notify:batchRemove', 2, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (90, 84, '我的通知', 'oa/notify/selfNotify', '', 1, 'fa fa-envelope-square', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (91, 0, '系统监控', '', '', 0, 'fa fa-video-camera', 5, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (92, 91, '在线用户', 'sys/online', '', 1, 'fa fa-user', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (93, 0, '工作流程', '', '', 0, 'fa fa-print', 6, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (94, 93, '模型管理', 'activiti/model', '', 1, 'fa fa-sort-amount-asc', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (95, 94, '全部权限', '', 'activiti:model', 2, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (96, 93, '流程管理', 'activiti/process', '', 1, 'fa fa-flag', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (97, 0, '图表管理', '', '', 0, 'fa fa-bar-chart', 7, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (98, 97, '百度chart', 'chart/graph_echarts.html', '', 1, 'fa fa-area-chart', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (99, 96, '所有权限', '', 'act:process', 2, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (104, 77, 'swagger', 'swagger-ui.html', '', 1, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (106, 84, '请假管理', 'oa/leave', 'oa:leave', 1, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (107, 84, '我的待办', 'oa/work', 'oa:work:work', 1, '', NULL, NULL, NULL);
INSERT INTO `t_sys_menu`(`menu_id`, `parent_id`, `name`, `url`, `perms`, `type`, `icon`, `order_num`, `gmt_create`, `gmt_modified`) VALUES (108, 96, '节点权限', '', 'activiti:customActivities', 1, '', NULL, NULL, NULL);


-- ----------------------------
-- Records of t_sys_role
-- ----------------------------
INSERT INTO `t_sys_role` VALUES ('1', '超级用户角色', 'admin', '拥有最高权限', '2', '2017-08-12 00:43:52', '2017-08-12 19:14:59');
INSERT INTO `t_sys_role` VALUES ('59', '普通用户', 'common', '基本用户权限', null, null, null);
INSERT INTO `t_sys_role` VALUES ('60', '部门经理', 'deptManager', '负责小于3天的请假审批', null, null, null);
INSERT INTO `t_sys_role` VALUES ('61', '部门主管', 'deptLeader', '负责大于等于3天的请假审批', null, null, null);

-- ----------------------------
-- Records of t_sys_role_menu
-- ----------------------------
INSERT INTO `t_sys_role_menu` VALUES ('367', '44', '1');
INSERT INTO `t_sys_role_menu` VALUES ('368', '44', '32');
INSERT INTO `t_sys_role_menu` VALUES ('369', '44', '33');
INSERT INTO `t_sys_role_menu` VALUES ('370', '44', '34');
INSERT INTO `t_sys_role_menu` VALUES ('371', '44', '35');
INSERT INTO `t_sys_role_menu` VALUES ('372', '44', '28');
INSERT INTO `t_sys_role_menu` VALUES ('373', '44', '29');
INSERT INTO `t_sys_role_menu` VALUES ('374', '44', '30');
INSERT INTO `t_sys_role_menu` VALUES ('375', '44', '38');
INSERT INTO `t_sys_role_menu` VALUES ('376', '44', '4');
INSERT INTO `t_sys_role_menu` VALUES ('377', '44', '27');
INSERT INTO `t_sys_role_menu` VALUES ('378', '45', '38');
INSERT INTO `t_sys_role_menu` VALUES ('379', '46', '3');
INSERT INTO `t_sys_role_menu` VALUES ('380', '46', '20');
INSERT INTO `t_sys_role_menu` VALUES ('381', '46', '21');
INSERT INTO `t_sys_role_menu` VALUES ('382', '46', '22');
INSERT INTO `t_sys_role_menu` VALUES ('383', '46', '23');
INSERT INTO `t_sys_role_menu` VALUES ('384', '46', '11');
INSERT INTO `t_sys_role_menu` VALUES ('385', '46', '12');
INSERT INTO `t_sys_role_menu` VALUES ('386', '46', '13');
INSERT INTO `t_sys_role_menu` VALUES ('387', '46', '14');
INSERT INTO `t_sys_role_menu` VALUES ('388', '46', '24');
INSERT INTO `t_sys_role_menu` VALUES ('389', '46', '25');
INSERT INTO `t_sys_role_menu` VALUES ('390', '46', '26');
INSERT INTO `t_sys_role_menu` VALUES ('391', '46', '15');
INSERT INTO `t_sys_role_menu` VALUES ('392', '46', '2');
INSERT INTO `t_sys_role_menu` VALUES ('393', '46', '6');
INSERT INTO `t_sys_role_menu` VALUES ('394', '46', '7');
INSERT INTO `t_sys_role_menu` VALUES ('598', '50', '38');
INSERT INTO `t_sys_role_menu` VALUES ('632', '38', '42');
INSERT INTO `t_sys_role_menu` VALUES ('737', '51', '38');
INSERT INTO `t_sys_role_menu` VALUES ('738', '51', '39');
INSERT INTO `t_sys_role_menu` VALUES ('739', '51', '40');
INSERT INTO `t_sys_role_menu` VALUES ('740', '51', '41');
INSERT INTO `t_sys_role_menu` VALUES ('741', '51', '4');
INSERT INTO `t_sys_role_menu` VALUES ('742', '51', '32');
INSERT INTO `t_sys_role_menu` VALUES ('743', '51', '33');
INSERT INTO `t_sys_role_menu` VALUES ('744', '51', '34');
INSERT INTO `t_sys_role_menu` VALUES ('745', '51', '35');
INSERT INTO `t_sys_role_menu` VALUES ('746', '51', '27');
INSERT INTO `t_sys_role_menu` VALUES ('747', '51', '28');
INSERT INTO `t_sys_role_menu` VALUES ('748', '51', '29');
INSERT INTO `t_sys_role_menu` VALUES ('749', '51', '30');
INSERT INTO `t_sys_role_menu` VALUES ('750', '51', '1');
INSERT INTO `t_sys_role_menu` VALUES ('1064', '54', '53');
INSERT INTO `t_sys_role_menu` VALUES ('1095', '55', '2');
INSERT INTO `t_sys_role_menu` VALUES ('1096', '55', '6');
INSERT INTO `t_sys_role_menu` VALUES ('1097', '55', '7');
INSERT INTO `t_sys_role_menu` VALUES ('1098', '55', '3');
INSERT INTO `t_sys_role_menu` VALUES ('1099', '55', '50');
INSERT INTO `t_sys_role_menu` VALUES ('1100', '55', '49');
INSERT INTO `t_sys_role_menu` VALUES ('1101', '55', '1');
INSERT INTO `t_sys_role_menu` VALUES ('1856', '53', '28');
INSERT INTO `t_sys_role_menu` VALUES ('1857', '53', '29');
INSERT INTO `t_sys_role_menu` VALUES ('1858', '53', '30');
INSERT INTO `t_sys_role_menu` VALUES ('1859', '53', '27');
INSERT INTO `t_sys_role_menu` VALUES ('1860', '53', '57');
INSERT INTO `t_sys_role_menu` VALUES ('1861', '53', '71');
INSERT INTO `t_sys_role_menu` VALUES ('1862', '53', '48');
INSERT INTO `t_sys_role_menu` VALUES ('1863', '53', '72');
INSERT INTO `t_sys_role_menu` VALUES ('1864', '53', '1');
INSERT INTO `t_sys_role_menu` VALUES ('1865', '53', '7');
INSERT INTO `t_sys_role_menu` VALUES ('1866', '53', '55');
INSERT INTO `t_sys_role_menu` VALUES ('1867', '53', '56');
INSERT INTO `t_sys_role_menu` VALUES ('1868', '53', '62');
INSERT INTO `t_sys_role_menu` VALUES ('1869', '53', '15');
INSERT INTO `t_sys_role_menu` VALUES ('1870', '53', '2');
INSERT INTO `t_sys_role_menu` VALUES ('1871', '53', '61');
INSERT INTO `t_sys_role_menu` VALUES ('1872', '53', '20');
INSERT INTO `t_sys_role_menu` VALUES ('1873', '53', '21');
INSERT INTO `t_sys_role_menu` VALUES ('1874', '53', '22');
INSERT INTO `t_sys_role_menu` VALUES ('2084', '56', '68');
INSERT INTO `t_sys_role_menu` VALUES ('2085', '56', '60');
INSERT INTO `t_sys_role_menu` VALUES ('2086', '56', '59');
INSERT INTO `t_sys_role_menu` VALUES ('2087', '56', '58');
INSERT INTO `t_sys_role_menu` VALUES ('2088', '56', '51');
INSERT INTO `t_sys_role_menu` VALUES ('2089', '56', '50');
INSERT INTO `t_sys_role_menu` VALUES ('2090', '56', '49');
INSERT INTO `t_sys_role_menu` VALUES ('2243', '48', '72');
INSERT INTO `t_sys_role_menu` VALUES ('2247', '63', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('2248', '63', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2249', '63', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2250', '63', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2251', '63', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2252', '64', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2253', '64', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2254', '64', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2255', '64', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2256', '64', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2257', '64', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2258', '65', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2259', '65', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2260', '65', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2262', '67', '48');
INSERT INTO `t_sys_role_menu` VALUES ('2263', '68', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2264', '68', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2265', '69', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2266', '69', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2267', '69', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2268', '69', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2269', '69', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2270', '69', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2271', '70', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2272', '70', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2273', '70', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2274', '70', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2275', '70', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2276', '70', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2277', '71', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2278', '72', '59');
INSERT INTO `t_sys_role_menu` VALUES ('2279', '73', '48');
INSERT INTO `t_sys_role_menu` VALUES ('2280', '74', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2281', '74', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2282', '75', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2283', '75', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2284', '76', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2285', '76', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2286', '76', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2287', '76', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2288', '76', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2289', '76', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2292', '78', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2293', '78', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2294', '78', null);
INSERT INTO `t_sys_role_menu` VALUES ('2295', '78', null);
INSERT INTO `t_sys_role_menu` VALUES ('2296', '78', null);
INSERT INTO `t_sys_role_menu` VALUES ('2308', '80', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2309', '80', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2310', '80', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('2311', '80', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2312', '80', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2328', '79', '72');
INSERT INTO `t_sys_role_menu` VALUES ('2329', '79', '48');
INSERT INTO `t_sys_role_menu` VALUES ('2330', '79', '77');
INSERT INTO `t_sys_role_menu` VALUES ('2331', '79', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2332', '79', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2333', '79', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2334', '79', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2335', '79', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2336', '79', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2337', '79', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('2338', '77', '89');
INSERT INTO `t_sys_role_menu` VALUES ('2339', '77', '88');
INSERT INTO `t_sys_role_menu` VALUES ('2340', '77', '87');
INSERT INTO `t_sys_role_menu` VALUES ('2341', '77', '86');
INSERT INTO `t_sys_role_menu` VALUES ('2342', '77', '85');
INSERT INTO `t_sys_role_menu` VALUES ('2343', '77', '84');
INSERT INTO `t_sys_role_menu` VALUES ('2344', '77', '72');
INSERT INTO `t_sys_role_menu` VALUES ('2345', '77', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('2346', '77', '77');
INSERT INTO `t_sys_role_menu` VALUES ('2974', '57', '93');
INSERT INTO `t_sys_role_menu` VALUES ('2975', '57', '99');
INSERT INTO `t_sys_role_menu` VALUES ('2976', '57', '95');
INSERT INTO `t_sys_role_menu` VALUES ('2977', '57', '101');
INSERT INTO `t_sys_role_menu` VALUES ('2978', '57', '96');
INSERT INTO `t_sys_role_menu` VALUES ('2979', '57', '94');
INSERT INTO `t_sys_role_menu` VALUES ('2980', '57', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('2981', '58', '93');
INSERT INTO `t_sys_role_menu` VALUES ('2982', '58', '99');
INSERT INTO `t_sys_role_menu` VALUES ('2983', '58', '95');
INSERT INTO `t_sys_role_menu` VALUES ('2984', '58', '101');
INSERT INTO `t_sys_role_menu` VALUES ('2985', '58', '96');
INSERT INTO `t_sys_role_menu` VALUES ('2986', '58', '94');
INSERT INTO `t_sys_role_menu` VALUES ('2987', '58', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('3466', '59', '98');
INSERT INTO `t_sys_role_menu` VALUES ('3467', '59', '101');
INSERT INTO `t_sys_role_menu` VALUES ('3468', '59', '99');
INSERT INTO `t_sys_role_menu` VALUES ('3469', '59', '95');
INSERT INTO `t_sys_role_menu` VALUES ('3470', '59', '105');
INSERT INTO `t_sys_role_menu` VALUES ('3471', '59', '90');
INSERT INTO `t_sys_role_menu` VALUES ('3472', '59', '89');
INSERT INTO `t_sys_role_menu` VALUES ('3473', '59', '88');
INSERT INTO `t_sys_role_menu` VALUES ('3474', '59', '87');
INSERT INTO `t_sys_role_menu` VALUES ('3475', '59', '86');
INSERT INTO `t_sys_role_menu` VALUES ('3476', '59', '68');
INSERT INTO `t_sys_role_menu` VALUES ('3477', '59', '60');
INSERT INTO `t_sys_role_menu` VALUES ('3478', '59', '59');
INSERT INTO `t_sys_role_menu` VALUES ('3479', '59', '58');
INSERT INTO `t_sys_role_menu` VALUES ('3480', '59', '51');
INSERT INTO `t_sys_role_menu` VALUES ('3481', '59', '76');
INSERT INTO `t_sys_role_menu` VALUES ('3482', '59', '75');
INSERT INTO `t_sys_role_menu` VALUES ('3483', '59', '74');
INSERT INTO `t_sys_role_menu` VALUES ('3484', '59', '62');
INSERT INTO `t_sys_role_menu` VALUES ('3485', '59', '56');
INSERT INTO `t_sys_role_menu` VALUES ('3486', '59', '55');
INSERT INTO `t_sys_role_menu` VALUES ('3487', '59', '15');
INSERT INTO `t_sys_role_menu` VALUES ('3488', '59', '26');
INSERT INTO `t_sys_role_menu` VALUES ('3489', '59', '25');
INSERT INTO `t_sys_role_menu` VALUES ('3490', '59', '24');
INSERT INTO `t_sys_role_menu` VALUES ('3491', '59', '14');
INSERT INTO `t_sys_role_menu` VALUES ('3492', '59', '13');
INSERT INTO `t_sys_role_menu` VALUES ('3493', '59', '12');
INSERT INTO `t_sys_role_menu` VALUES ('3494', '59', '61');
INSERT INTO `t_sys_role_menu` VALUES ('3495', '59', '22');
INSERT INTO `t_sys_role_menu` VALUES ('3496', '59', '21');
INSERT INTO `t_sys_role_menu` VALUES ('3497', '59', '20');
INSERT INTO `t_sys_role_menu` VALUES ('3498', '59', '83');
INSERT INTO `t_sys_role_menu` VALUES ('3499', '59', '81');
INSERT INTO `t_sys_role_menu` VALUES ('3500', '59', '80');
INSERT INTO `t_sys_role_menu` VALUES ('3501', '59', '79');
INSERT INTO `t_sys_role_menu` VALUES ('3502', '59', '71');
INSERT INTO `t_sys_role_menu` VALUES ('3503', '59', '97');
INSERT INTO `t_sys_role_menu` VALUES ('3504', '59', '96');
INSERT INTO `t_sys_role_menu` VALUES ('3505', '59', '94');
INSERT INTO `t_sys_role_menu` VALUES ('3506', '59', '93');
INSERT INTO `t_sys_role_menu` VALUES ('3507', '59', '85');
INSERT INTO `t_sys_role_menu` VALUES ('3508', '59', '50');
INSERT INTO `t_sys_role_menu` VALUES ('3509', '59', '49');
INSERT INTO `t_sys_role_menu` VALUES ('3510', '59', '73');
INSERT INTO `t_sys_role_menu` VALUES ('3511', '59', '7');
INSERT INTO `t_sys_role_menu` VALUES ('3512', '59', '6');
INSERT INTO `t_sys_role_menu` VALUES ('3513', '59', '2');
INSERT INTO `t_sys_role_menu` VALUES ('3514', '59', '3');
INSERT INTO `t_sys_role_menu` VALUES ('3515', '59', '78');
INSERT INTO `t_sys_role_menu` VALUES ('3516', '59', '1');
INSERT INTO `t_sys_role_menu` VALUES ('3517', '59', '-1');
INSERT INTO `t_sys_role_menu` VALUES ('3518', '59', '84');
INSERT INTO `t_sys_role_menu` VALUES ('3585', '1', '98');
INSERT INTO `t_sys_role_menu` VALUES ('3586', '1', '101');
INSERT INTO `t_sys_role_menu` VALUES ('3587', '1', '99');
INSERT INTO `t_sys_role_menu` VALUES ('3588', '1', '95');
INSERT INTO `t_sys_role_menu` VALUES ('3589', '1', '92');
INSERT INTO `t_sys_role_menu` VALUES ('3590', '1', '57');
INSERT INTO `t_sys_role_menu` VALUES ('3591', '1', '30');
INSERT INTO `t_sys_role_menu` VALUES ('3592', '1', '29');
INSERT INTO `t_sys_role_menu` VALUES ('3593', '1', '28');
INSERT INTO `t_sys_role_menu` VALUES ('3594', '1', '107');
INSERT INTO `t_sys_role_menu` VALUES ('3595', '1', '106');
INSERT INTO `t_sys_role_menu` VALUES ('3596', '1', '105');
INSERT INTO `t_sys_role_menu` VALUES ('3597', '1', '90');
INSERT INTO `t_sys_role_menu` VALUES ('3598', '1', '89');
INSERT INTO `t_sys_role_menu` VALUES ('3599', '1', '88');
INSERT INTO `t_sys_role_menu` VALUES ('3600', '1', '87');
INSERT INTO `t_sys_role_menu` VALUES ('3601', '1', '86');
INSERT INTO `t_sys_role_menu` VALUES ('3602', '1', '104');
INSERT INTO `t_sys_role_menu` VALUES ('3603', '1', '72');
INSERT INTO `t_sys_role_menu` VALUES ('3604', '1', '48');
INSERT INTO `t_sys_role_menu` VALUES ('3605', '1', '68');
INSERT INTO `t_sys_role_menu` VALUES ('3606', '1', '60');
INSERT INTO `t_sys_role_menu` VALUES ('3607', '1', '59');
INSERT INTO `t_sys_role_menu` VALUES ('3608', '1', '58');
INSERT INTO `t_sys_role_menu` VALUES ('3609', '1', '51');
INSERT INTO `t_sys_role_menu` VALUES ('3610', '1', '76');
INSERT INTO `t_sys_role_menu` VALUES ('3611', '1', '75');
INSERT INTO `t_sys_role_menu` VALUES ('3612', '1', '74');
INSERT INTO `t_sys_role_menu` VALUES ('3613', '1', '62');
INSERT INTO `t_sys_role_menu` VALUES ('3614', '1', '56');
INSERT INTO `t_sys_role_menu` VALUES ('3615', '1', '55');
INSERT INTO `t_sys_role_menu` VALUES ('3616', '1', '15');
INSERT INTO `t_sys_role_menu` VALUES ('3617', '1', '26');
INSERT INTO `t_sys_role_menu` VALUES ('3618', '1', '25');
INSERT INTO `t_sys_role_menu` VALUES ('3619', '1', '24');
INSERT INTO `t_sys_role_menu` VALUES ('3620', '1', '14');
INSERT INTO `t_sys_role_menu` VALUES ('3621', '1', '13');
INSERT INTO `t_sys_role_menu` VALUES ('3622', '1', '12');
INSERT INTO `t_sys_role_menu` VALUES ('3623', '1', '61');
INSERT INTO `t_sys_role_menu` VALUES ('3624', '1', '22');
INSERT INTO `t_sys_role_menu` VALUES ('3625', '1', '21');
INSERT INTO `t_sys_role_menu` VALUES ('3626', '1', '20');
INSERT INTO `t_sys_role_menu` VALUES ('3627', '1', '83');
INSERT INTO `t_sys_role_menu` VALUES ('3628', '1', '81');
INSERT INTO `t_sys_role_menu` VALUES ('3629', '1', '80');
INSERT INTO `t_sys_role_menu` VALUES ('3630', '1', '79');
INSERT INTO `t_sys_role_menu` VALUES ('3631', '1', '71');
INSERT INTO `t_sys_role_menu` VALUES ('3632', '1', '97');
INSERT INTO `t_sys_role_menu` VALUES ('3633', '1', '94');
INSERT INTO `t_sys_role_menu` VALUES ('3634', '1', '27');
INSERT INTO `t_sys_role_menu` VALUES ('3635', '1', '91');
INSERT INTO `t_sys_role_menu` VALUES ('3636', '1', '85');
INSERT INTO `t_sys_role_menu` VALUES ('3637', '1', '84');
INSERT INTO `t_sys_role_menu` VALUES ('3638', '1', '77');
INSERT INTO `t_sys_role_menu` VALUES ('3639', '1', '50');
INSERT INTO `t_sys_role_menu` VALUES ('3640', '1', '49');
INSERT INTO `t_sys_role_menu` VALUES ('3641', '1', '73');
INSERT INTO `t_sys_role_menu` VALUES ('3642', '1', '7');
INSERT INTO `t_sys_role_menu` VALUES ('3643', '1', '6');
INSERT INTO `t_sys_role_menu` VALUES ('3644', '1', '2');
INSERT INTO `t_sys_role_menu` VALUES ('3645', '1', '3');
INSERT INTO `t_sys_role_menu` VALUES ('3646', '1', '78');
INSERT INTO `t_sys_role_menu` VALUES ('3647', '1', '1');
INSERT INTO `t_sys_role_menu` VALUES ('3648', '1', '108');
INSERT INTO `t_sys_role_menu` VALUES ('3649', '1', '96');
INSERT INTO `t_sys_role_menu` VALUES ('3650', '1', '93');
INSERT INTO `t_sys_role_menu` VALUES ('3651', '1', '-1');

-- ----------------------------
-- Records of t_sys_task
-- ----------------------------
INSERT INTO `t_sys_task` VALUES ('2', '0/10 * * * * ?', 'run1', '1', '', '4028ea815a3d2a8c015a3d2f8d2a0002', 'com.bootdo.common.task.WelcomeJob', '2017-05-19 18:30:56', '0', 'group1', '2017-05-19 18:31:07', null, '', 'welcomJob');

-- ----------------------------
-- Records of t_sys_user
-- ----------------------------
INSERT INTO `t_sys_user` VALUES ('1', 'admin', '超级管理员', '27bd386e70f280e24c2f4f2a549b82cf', '6', 'admin@example.com', '17699999999', '1', '1', '2017-08-15 21:40:39', '2017-08-15 21:41:00', '96', '2017-12-14 00:00:00', '138', 'ccc', '122;121;', '北京市', '北京市市辖区', '东城区');
INSERT INTO `t_sys_user` VALUES ('2', 'test', '临时用户', '6cf3bb3deba2aadbd41ec9a22511084e', '6', 'test@bootdo.com', null, '1', '1', '2017-08-14 13:43:05', '2017-08-14 21:15:36', null, null, null, null, null, null, null, null);

-- ----------------------------
-- Records of t_sys_user_role
-- ----------------------------
INSERT INTO `t_sys_user_role` VALUES ('73', '30', '48');
INSERT INTO `t_sys_user_role` VALUES ('74', '30', '49');
INSERT INTO `t_sys_user_role` VALUES ('75', '30', '50');
INSERT INTO `t_sys_user_role` VALUES ('76', '31', '48');
INSERT INTO `t_sys_user_role` VALUES ('77', '31', '49');
INSERT INTO `t_sys_user_role` VALUES ('78', '31', '52');
INSERT INTO `t_sys_user_role` VALUES ('79', '32', '48');
INSERT INTO `t_sys_user_role` VALUES ('80', '32', '49');
INSERT INTO `t_sys_user_role` VALUES ('81', '32', '50');
INSERT INTO `t_sys_user_role` VALUES ('82', '32', '51');
INSERT INTO `t_sys_user_role` VALUES ('83', '32', '52');
INSERT INTO `t_sys_user_role` VALUES ('84', '33', '38');
INSERT INTO `t_sys_user_role` VALUES ('85', '33', '49');
INSERT INTO `t_sys_user_role` VALUES ('86', '33', '52');
INSERT INTO `t_sys_user_role` VALUES ('87', '34', '50');
INSERT INTO `t_sys_user_role` VALUES ('88', '34', '51');
INSERT INTO `t_sys_user_role` VALUES ('89', '34', '52');
INSERT INTO `t_sys_user_role` VALUES ('106', '124', '1');
INSERT INTO `t_sys_user_role` VALUES ('111', '2', '1');
INSERT INTO `t_sys_user_role` VALUES ('113', '131', '48');
INSERT INTO `t_sys_user_role` VALUES ('117', '135', '1');
INSERT INTO `t_sys_user_role` VALUES ('123', '130', '1');
INSERT INTO `t_sys_user_role` VALUES ('124', null, '48');
INSERT INTO `t_sys_user_role` VALUES ('127', '123', '48');
INSERT INTO `t_sys_user_role` VALUES ('132', '36', '48');
INSERT INTO `t_sys_user_role` VALUES ('133', '1', '61');
INSERT INTO `t_sys_user_role` VALUES ('134', '1', '60');
INSERT INTO `t_sys_user_role` VALUES ('135', '1', '1');
INSERT INTO `t_sys_user_role` VALUES ('136', '132', '1');
INSERT INTO `t_sys_user_role` VALUES ('137', '134', '1');